#################
# Global settings
#----------------
sonar.host.url=https://sonarent.corp.intranet

# Debug Mode
sonar.log.level=INFO

# Required metadata
sonar.projectKey=OE-TRANSFORM-OE-Transform-adaptor-service_scan
sonar.projectName=OE-TRANSFORM-OE-Transform-adaptor-service
#sonar.projectVersion=1.0

# Path to the parent source code directory.
# Path is relative to the sonar-project.properties file or the module root. Replace "\" by "/" on Windows.
sonar.sources=src/main
sonar.java.binaries=target/classes
sonar.tests=src/test
sonar.coverage.jacoco.xmlReportPaths=target/**/jacoco.xml
sonar.junit.reportPaths=target/surefire-reports/*.xml

########################

# Comma-separated list of files to be ignored
# ** ignores zero or more directories
# *  ignores zero or more characters
sonar.exclusions=**/config/**/*,**/constants/**/*,**/exception/**/*,**/model/**/*,**/propertyreader/**/*,**/test/**/*

######################
# Pull Request
#sonar.pullrequest.branch=
#sonar.pullrequest.key=
#sonar.pullrequest.base=master

